<table width='200' border='0' cellpadding='0' cellspacing='0'><tr><td height='36'><a href='#' onClick='go_best_shop();'><img src='/images/week_bestshop_01.gif' alt='주간 베스트샵' width='200' height='36' border='0'></a></td></tr><tr><td align='center' background='/images/week_bestshop_02.gif'><table width='170' border='0' cellspacing='0' cellpadding='0'>
<tr><td width='17' height='20'><img src='/img/nomber_01.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('(주)좋은샵');">(주)좋은샵</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
<tr><td width='17' height='20'><img src='/img/nomber_02.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('(주)맛있는고기');">(주)맛있는고기</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
<tr><td width='17' height='20'><img src='/img/nomber_03.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('굿샵');">굿샵</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
<tr><td width='17' height='20'><img src='/img/nomber_04.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('굿샵2호점');">굿샵2호점</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
<tr><td width='17' height='20'><img src='/img/nomber_05.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('(주)이루리');">(주)이루리</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
<tr><td width='17' height='20'><img src='/img/nomber_06.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('수야몰');">수야몰</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
<tr><td width='17' height='20'><img src='/img/nomber_07.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('심심타파샵');">심심타파샵</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
<tr><td width='17' height='20'><img src='/img/nomber_08.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('란샵');">란샵</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
<tr><td width='17' height='20'><img src='/img/nomber_09.gif' width='12' height='12'></td><td class='shopname'><b><font color='#333333'><a href='#' onClick="go_shop_info('행사몰');">행사몰</a></font></b></td><td width='20' align='center'><img src='/img/icon_tie.gif' width='10' height='10'></td><td width='30' align='center' class='nomber'>0</td></tr><tr><td height='1' colspan='4' background='/img/dot_garo_mini.gif'></td></tr>
</table></td></tr><tr><td height='13'><img src='/images/week_bestshop_03.gif' width='200' height='13' alt=''></td></tr></table>
