
<html>
<head>
<title>코디탑10 비밀번호</title>
<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">
<style>
body, p, div, td, select, br, table, input, textarea { font-family: "굴림"; font-size: 9pt; color:#777777; line-height: 120% }
A:link    { text-decoration:none; font-size:9pt; color: #6A6A6A}
A:visited { text-decoration:none; font-size:9pt; color: #6A6A6A}
A:hover  { text-decoration:none; font-size:9pt; color: #000000}
</style>
</head>

<body>
<table width="600" height="0%" border="0" cellpadding="0" cellspacing="1" bgcolor="D3D3D3">
  <tr> 
    <td  bgcolor="#FFFFFF" height="470"><table width="588" height="100%" border="0" align="center" cellpadding="0" cellspacing="0">
        <tr> 
          <td colspan="3"></td>
        </tr>
        <tr> 
          <td colspan="3"><img src="http://www.supert.co.kr/img/logo.gif" width="77" height="43"></td>
        </tr>
        <tr> 
     
        </tr>
        <tr> 
          <td colspan="3"><table width="588" border="0" cellpadding="0" cellspacing="0">
              <tr> 
                <td width="10"><img src="http://www.assalabia.com/help/img/id_search/p1_1.gif" width="10" height="27"></td>
                <td width="554" bgcolor="72AEDF"><strong><font color="#FFFFFF">아이디/비밀번호 
                  찾기</font></strong></td>
                <td width="10"><img src="http://www.assalabia.com/help/img/id_search/p1_2.gif" width="10" height="27"></td>
              </tr>
            </table></td>
        </tr>
        <tr> 
          <td width="22"></td>
          <td width="565"><br> <br>
            안녕하세요. 코디탑10 입니다.<br>
            #name# 님의 코디탑10 아이디/비밀번호 찾기에 대한 결과입니다.</td>
        </tr>
        <tr> 
          <td height="20" colspan="3"> </td>
        </tr>
        <tr> 
          <td colspan="3"><table width="240" height="80" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr> 
                <td width="10" height="10"><img src="http://www.assalabia.com/help/img/id_search/p1.gif" width="10" height="10"></td>
                <td bgcolor="#D8D8D8"></td>
                <td width="10"><img src="http://www.assalabia.com/help/img/id_search/p2.gif" width="10" height="10"></td>
              </tr>
              <tr bgcolor="#D8D8D8"> 
                <td></td>
                <td bgcolor="#D8D8D8" align="center" height="0"><table width="210" height="54" border="0" cellpadding="0" cellspacing="1">
                    <tr> 
                      <td width="36%" bgcolor="DFF0FD"><div align="center">아이디</div></td>
                      <td width="64%" bgcolor="#FFFFFF">&nbsp;#id#</td>
                    </tr>
                    <tr> 
                      <td bgcolor="DFF0FD"><div align="center">비밀번호 </div></td>
                      <td bgcolor="#FFFFFF">&nbsp;#pw#</td>
                    </tr>
                  </table></td>
                <td></td>
              </tr>
              <tr> 
                <td height="10"><img src="http://www.assalabia.com/help/img/id_search/p3.gif" width="10" height="10"></td>
                <td bgcolor="#D8D8D8"></td>
                <td><img src="http://www.assalabia.com/help/img/id_search/p4.gif" width="10" height="10"></td>
              </tr>
            </table></td>
        </tr>
        <tr> 
          <td height="20" colspan="3">&nbsp;</td>
        </tr>
        <tr> 
          <td rowspan="2"></td>
          <td> 잊어버리시거나 누출되지 않도록 조심하시기 바랍니다.<br> <br>
            오늘도 코디탑10과 함께 즐거운 하루 되세요~!<br>
            감사합니다. <br> <br> <br>
            from. coditop10</td>
          <td width="1" rowspan="2"></td>
        </tr>
        <tr> 
          <td><div align="right">ⓒ2007 coditop10.com All rights reserved.</div></td>
        </tr>
        <tr> </tr>
      </table></td>
  </tr>
</table>
</body>
</html>

